# Numpy_Assignment_2::

## Question:1

### Convert a 1D array to a 2D array with 2 rows?

#### Desired output::

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [1]:
import numpy as np
arr = np.array([0, 1, 2, 3, 4 , 5, 6, 7, 8, 9])
arr = arr.reshape((2,5))
print(arr)

[[0 1 2 3 4]
 [5 6 7 8 9]]


## Question:2

###  How to stack two arrays vertically?

#### Desired Output::

In [2]:
arr1 = np.array([[0, 1, 2, 3, 4],
                [5, 6, 7, 8, 9]])
arr2 = np.ones((2,5))
arr3 = np.vstack((arr1,arr2))
arr3 = arr3.astype('int32')
print(arr3)

[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


## Question:3

### How to stack two arrays horizontally?

#### Desired Output::

In [3]:
arr4 = np.hstack((arr1,arr2))
arr4 = arr4.astype('int32')
print(arr4)

[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


## Question:4

### How to convert an array of arrays into a flat 1d array?

#### Desired Output::

In [4]:
arr = arr.flatten()
print(arr)

[0 1 2 3 4 5 6 7 8 9]


## Question:5

### How to Convert higher dimension into one dimension?

#### Desired Output::

In [5]:
arr5 = np.array([
    [ 0, 1, 2],
    [ 3, 4, 5],
    [ 6, 7, 8],
    [ 9, 10, 11],
    [12, 13, 14]
])
arr5 = np.ravel(arr5)
print(arr5)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


## Question:6

### Convert one dimension to higher dimension?

#### Desired Output::

In [6]:
arr5.reshape(5,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

## Question:7

### Create 5x5 an array and find the square of an array?

In [7]:
arr6 = np.random.randint(1,25, size = (5,5))
print("Original Array: \n")
print (arr6)
print("\n")
print("Square of Array: \n")
print(arr6 ** 2)

Original Array: 

[[15  1 20 24 16]
 [13 23 10  8 22]
 [19 20 12 19  3]
 [ 5  3  8 24 15]
 [23 13 22 15 17]]


Square of Array: 

[[225   1 400 576 256]
 [169 529 100  64 484]
 [361 400 144 361   9]
 [ 25   9  64 576 225]
 [529 169 484 225 289]]


## Question:8

### Create 5x6 an array and find the mean?

In [8]:
arr8 = np.random.randint(1,20, size = (5,6))
print("Original Array: \n")
print (arr8)
print("\n")
print("Mean of Array: \n")
print(arr8.mean())

Original Array: 

[[ 5 15 16 10 17  9]
 [14 18  9 13 19  4]
 [18  9  7 11 16 17]
 [ 8  5 11 12  5  3]
 [ 3  6  7 19  3 19]]


Mean of Array: 

10.933333333333334


## Question:9

### Find the standard deviation of the previous array in Q8?

In [9]:
print("Original Array: \n")
print (arr8)
print("\n")
print("Standard deviation of Array: \n")
print(np.std(arr8))

Original Array: 

[[ 5 15 16 10 17  9]
 [14 18  9 13 19  4]
 [18  9  7 11 16 17]
 [ 8  5 11 12  5  3]
 [ 3  6  7 19  3 19]]


Standard deviation of Array: 

5.3847521350156455


## Question:10

### Find the median of the previous array in Q8?

In [10]:
print("Original Array: \n")
print (arr8)
print("\n")
print("Median of Array: \n")
print(np.median(arr8))

Original Array: 

[[ 5 15 16 10 17  9]
 [14 18  9 13 19  4]
 [18  9  7 11 16 17]
 [ 8  5 11 12  5  3]
 [ 3  6  7 19  3 19]]


Median of Array: 

10.5


## Question:11

### Find the transpose of the previous array in Q8?

In [11]:
print("Original Array: \n")
print (arr8)
print("\n")
print("Transpose of Array: \n")
print(np.transpose(arr8))

Original Array: 

[[ 5 15 16 10 17  9]
 [14 18  9 13 19  4]
 [18  9  7 11 16 17]
 [ 8  5 11 12  5  3]
 [ 3  6  7 19  3 19]]


Transpose of Array: 

[[ 5 14 18  8  3]
 [15 18  9  5  6]
 [16  9  7 11  7]
 [10 13 11 12 19]
 [17 19 16  5  3]
 [ 9  4 17  3 19]]


## Question:12

### Create a 4x4 an array and find the sum of diagonal elements?

In [12]:
arr7 = np.random.randint(1,20, size = (4,4))
print("Original Array: \n")
print (arr7)
print("\n")
print("Sum of diagonal elements of Array: \n")
print(np.trace(arr7))

Original Array: 

[[19  2  9  1]
 [ 1 14  1  6]
 [ 9  2 10 14]
 [ 3  8 17 10]]


Sum of diagonal elements of Array: 

53


## Question:13

### Find the determinant of the previous array in Q12?

In [13]:
print("Original Array: \n")
print (arr7)
print("\n")
print("Determinant of Array: \n")
print(np.linalg.det(arr7))

Original Array: 

[[19  2  9  1]
 [ 1 14  1  6]
 [ 9  2 10 14]
 [ 3  8 17 10]]


Determinant of Array: 

-42918.00000000001


## Question:14

### Find the 5th and 95th percentile of an array?

In [14]:
print("Original Array: \n")
print (arr7)
print("\n")
print(f"5th percentile of array: {np.percentile(arr7, 5)}")
print(f"95th percentile of array: {np.percentile(arr7, 95)}")

Original Array: 

[[19  2  9  1]
 [ 1 14  1  6]
 [ 9  2 10 14]
 [ 3  8 17 10]]


5th percentile of array: 1.0
95th percentile of array: 17.5


## Question:15

### How to find if a given array has any null values?

In [15]:
np.isnan(arr7).any()

False